config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  # Defines the root path route ("/")
   root "users#index"
  resources :users do
    resources :posts  # Define the route for the user's posts
  end
  
  resources :posts, only: [:new, :create]
  resources :comments, only: [:new, :create]
  resources :likes, only: [:new, :create]

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  def update_comment_counter
    num = Post.find_by(id: post_id).comments_counter.to_i
    Post.find_by(id: post_id).update(comments_counter: num + 1)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  def update_like_counter
    num = Post.find_by(id: post_id).likes_counter.to_i
    Post.find_by(id: post_id).update(likes_counter: num + 1)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments

  def update_post_counter
    num = User.find_by(id: author_id).posts_counter.to_i
    User.find_by(id: author_id).update(posts_counter: num + 1)
  end

  def recent_comments
    Comment.where(post_id: id).limit(5).order(created_at: :desc)
  end

  validates :title, presence: true, length: { in: 0..250 }
  validates :comments_counter, presence: true, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, presence: true, numericality: { greater_than_or_equal_to: 0, only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  def recent_post
    Post.where(author_id: id).limit(3).order(created_at: :desc)
  end

  def all_post
    Post.includes(:comments).where(author_id: id).order(created_at: :desc)
  end

  validates :name, presence: true
  validates :posts_counter, presence: true, numericality: { greater_than_or_equal_to: 0, only_integer: true }
end

app/controllers/application_controller.rb
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :photo, :posts_counter, :bio, :email, :password) }
    # devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :photo, :posts_counter, :bio, :email, :password, :current_password)}
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_user_and_post

  def new
    @comment = Comment.new
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to user_post_path(@user, @post), notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  private

  def find_user_and_post
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post

  def create
    @like = Like.new(user: current_user, post: @post)

    if @like.save
      flash.now[:notice] = 'Liked the post!'
      redirect_to user_post_path(@user, @post)
    else
      flash.now[:alert] = 'Failed to like the post!'
    end
  end

  private

  def find_post
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # Create action - Handle the creation of a new post

  def index
    @post = Post.includes(:comments).where(author_id: params[:user_id])
    @user = User.find_by(id: params[:user_id])
    @user_check = User.all
  end

  def new
    @post = @user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = 'Post created successfully'
      redirect_to @post
    else
      flash.now[:alert] = 'creation failed'
      render 'new'
    end
  end

  def show
    @post = Post.includes(:comments).find_by(id: params[:id])
    @comment = Comment.all.order(created_at: :desc)
    @user = User.find_by(id: params[:user_id])
    @user_check = User.all
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # index action
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  # We will add other action after
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1> Comment new </h1>
<!-- Form for creating a new comment -->
<%= form_with(model: current_user.comments.build, local: true) do |form| %>
  <%= form.label :content %>
  <%= form.text_area :content %><br>
  <%= form.submit 'Create Comment' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_likes_count.html.erb
<span class="span-post" data-target="likes_count">Likes: <%= post.likes.count %></span>

app/views/likes/create.js.erb
<%= turbo_stream.replace(
  @post, 
  partial: "likes_count",
  locals: { post: @post }
) %>

app/views/posts/index.html.erb
<div class="show-user">
<div class="container"><div class="cadre"><%= @user.photo %></div><div class="user"><h2><%= @user.name  %></h2> <p><span></span><span>Number of posts : <span><%= @user.posts_counter %></span></span></p></div></div>

<br>

<div id="pagination">
<% @post.each_with_index do |posts, idx|%>
    
    <% if idx < 3 %>
    <div class='post'>
        <span class='title'>
            <%= link_to posts.title, user_post_path(@user, posts) %>
        </span><br>
        <%= posts.text %>
        <p>
            <span></span>
            <span>comments : <span><% if (posts.comments_counter) %>
            <%= posts.comments_counter %>
            <% else %>
            <%= 0 %>
            <% end %>
            , likes : <span><% if (posts.likes_counter) %>
            <%= posts.likes_counter %>
            <% else %>
            <%= 0 %>
            <% end %></span></span>
            
        </p>
    </div>
    <div class='comment'>
    <% posts.recent_comments.each_with_index do |comments, idx|%>
        
            <% @user_check.each do |user_c|%>
                <% if(comments.user_id == user_c.id)%>
                    <%= user_c.name %>:<%= comments.text %><br>
                <% end %>
            <% end %>
        
        
    <% end %></div>
    
    <% end %> 
    
    
<% end %>
<button id="pagination-button">Pagination</button>
</div>


<div id="pagination-hide">
<% @post.each_with_index do |posts, idx|%>
    <% if idx > 2 %>
    <div class='post'>
        <span class='title'>
            <%= link_to posts.title, user_post_path(@user, posts) %>
        </span><br>
        <%= posts.text %>
        <p>
            <span></span>
            <span>comments : <span><% if (posts.comments_counter) %>
            <%= posts.comments_counter %>
            <% else %>
            <%= 0 %>
            <% end %>
            , likes : <span><% if (posts.likes_counter) %>
            <%= posts.likes_counter %>
            <% else %>
            <%= 0 %>
            <% end %></span></span>
            
        </p>
    </div>
    <div class='comment'>
    <% posts.recent_comments.each_with_index do |comments, idx|%>
        
            <% @user_check.each do |user_c|%>
                <% if(comments.user_id == user_c.id)%>
                    <%= user_c.name %>:<%= comments.text %><br>
                <% end %>
            <% end %>
        
        
    <% end %></div>
    <% end %>
    
<% end %>
</div>

<br>
</div> 

<script>
let button = document.querySelector('#pagination-button');
let big_post = document.querySelector('#pagination-hide');
let small_post = document.querySelector('#pagination');

button.addEventListener('click', () => {
    small_post.style.display = 'none';
    big_post.style.display = 'block';
});
</script>

app/views/posts/new.html.erb
<!-- Form for creating a new post -->
<h1>New Post</h1><br>
<%= form_with(model: current_user.posts.build, url: posts_path, local: true) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %><br><br>
  <%= form.label :content %>
  <%= form.text_area :text %><br><br>
  <%= form.submit 'Create Post' %>
<% end %>

app/views/posts/show.html.erb
<div class='show-post'>
    <span class='title'>
    <%= @post.title %> by <%= @user.name %>
    </span><br>
        <p class="ici">
            <span></span>
            <span>comments : <span><% if (@post.comments_counter) %>
            <%= @post.comments_counter %>
            <% else %>
            <%= 0 %>
            <% end %>
            , likes : <span><% if (@post.likes_counter) %>
            <%= @post.likes_counter %>
            
            <% else %>
            <%= 0 %>
            <% end %></span></span>
            
        </p>

        <div>
            <%= @post.text %>
        </div>
</div>

<div class='show-post'>
    <div >
        <% @comment.each do |comments|%>
            <% if(comments.post_id == @post.id)%>
                <% @user_check.each do |user_c|%>
                    <% if(comments.user_id == user_c.id)%>
                        <%= user_c.name %>:<%= comments.text %><br>
                    <% end %>
                <% end %>
            <% end %>
    
        <% end %>
    </div>

</div>

app/views/users/index.html.erb
<h1> User </h1>
<ul>
  <% @users.each do |user| %>
    <li class="container">
        <div class="cadre"><%= user.photo %></div>
        <div class="user">
            <h2><%= link_to user.name, user_path(user) %></h2>
            <p>
                <span></span>
                <span>Number of posts : <span><% if (user.posts_counter) %>
                <%= user.posts_counter %>
                <% else %>
                <%= 0 %>
                <% end %></span></span>
            </p>
        </div>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="show-user">
<div class="container"><div class="cadre"><%= @user.photo %></div><div class="user"><h2><%= @user.name  %></h2> <p><span></span><span>Number of posts : <span><%= @user.posts_counter %></span></span></p></div></div>

<p class='bio'><%= @user.bio %></p>
<br>
<div id="small-post">
<% @user.recent_post.each_with_index do |posts, idx|%>
    
    
    <div class='post'>
    <span class='title'>
    <%= link_to posts.title, user_posts_path(@user, posts) %>
    </span><br>
    <%= posts.text %>
    <p>
        <span></span>
        <span>comments : <span><% if (posts.comments_counter) %>
        <%= posts.comments_counter %>
        <% else %>
        <%= 0 %>
        <% end %>
        , likes : <span><% if (posts.likes_counter) %>
        <%= posts.likes_counter %>
        <% else %>
        <%= 0 %>
        <% end %></span></span>
        
    </p>
</div>
    
<% end %>
<button id="see_all"> See all </button>
</div>


<div id="big-post">
<% @user.all_post.each_with_index do |posts, idx|%>
    <div class='post'><span class='title'><%= link_to posts.title, user_posts_path(@user, posts) %><%= idx + 1 %></span>
    <br><%= posts.text %></div>
<% end %>
</div>
<br>
</div>
<script>
let button = document.querySelector('#see_all');
let big_post = document.querySelector('#big-post');
let small_post = document.querySelector('#small-post');

button.addEventListener('click', () => {
    small_post.style.display = 'none';
    big_post.style.display = 'block';
});
</script>